import { Match, Tournament, Team, User } from './types';

export const MOCK_USERS: User[] = [
  { id: '1', email: 'admin@draft.com', name: 'Carlos Ramírez', role: 'admin', avatarInitials: 'CR' },
  { id: '2', email: 'jugador@draft.com', name: 'Andrés Ruiz', role: 'player', team: 'Águilas FC', position: 'Delantero', avatarInitials: 'AR' },
  { id: '3', email: 'viewer@draft.com', name: 'Laura Gómez', role: 'viewer', avatarInitials: 'LG' },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 't1',
    name: 'Copa Draft — Julio 2025',
    sport: 'Fútbol',
    startDate: '2025-07-01',
    endDate: '2025-07-31',
    status: 'active',
    teamsCount: 8,
    matchesPlayed: 12,
    totalMatches: 28,
  },
  {
    id: 't2',
    name: 'Liga Nocturna Norte',
    sport: 'Fútbol',
    startDate: '2025-08-01',
    endDate: '2025-08-30',
    status: 'upcoming',
    teamsCount: 6,
    matchesPlayed: 0,
    totalMatches: 15,
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm1',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Águilas FC',
    teamAway: 'Los Tigres',
    field: 'Cancha 1',
    scheduledTime: '15:00',
    delayMinutes: 45,
    status: 'delayed',
    delayMessage: 'Partido anterior en tiempo extra',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm2',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Deportivo Sur',
    teamAway: 'Rionegro United',
    field: 'Cancha 2',
    scheduledTime: '15:30',
    delayMinutes: 0,
    status: 'live',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm3',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Embajadores',
    teamAway: 'Chapinero FC',
    field: 'Cancha 1',
    scheduledTime: '16:30',
    delayMinutes: 30,
    status: 'delayed',
    delayMessage: 'Lluvia en la cancha',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm4',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Los Halcones',
    teamAway: 'Bochica SC',
    field: 'Cancha 3',
    scheduledTime: '17:00',
    delayMinutes: 0,
    status: 'scheduled',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm5',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Leones del Norte',
    teamAway: 'Tigrillos',
    field: 'Cancha 2',
    scheduledTime: '17:30',
    delayMinutes: 0,
    status: 'scheduled',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm6',
    tournamentId: 't1',
    tournamentName: 'Copa Draft',
    teamHome: 'Águilas FC',
    teamAway: 'Deportivo Sur',
    field: 'Cancha 1',
    scheduledTime: '13:00',
    delayMinutes: 0,
    status: 'finished',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_STANDINGS: Team[] = [
  { id: 'team1', name: 'Águilas FC', wins: 4, losses: 1, draws: 1, points: 13, goalsFor: 14, goalsAgainst: 6 },
  { id: 'team2', name: 'Los Tigres', wins: 3, losses: 1, draws: 2, points: 11, goalsFor: 11, goalsAgainst: 8 },
  { id: 'team3', name: 'Deportivo Sur', wins: 3, losses: 2, draws: 0, points: 9, goalsFor: 9, goalsAgainst: 9 },
  { id: 'team4', name: 'Rionegro United', wins: 2, losses: 2, draws: 2, points: 8, goalsFor: 8, goalsAgainst: 10 },
  { id: 'team5', name: 'Embajadores', wins: 2, losses: 3, draws: 1, points: 7, goalsFor: 7, goalsAgainst: 11 },
  { id: 'team6', name: 'Chapinero FC', wins: 1, losses: 3, draws: 2, points: 5, goalsFor: 5, goalsAgainst: 10 },
  { id: 'team7', name: 'Los Halcones', wins: 1, losses: 4, draws: 1, points: 4, goalsFor: 6, goalsAgainst: 12 },
  { id: 'team8', name: 'Bochica SC', wins: 0, losses: 4, draws: 2, points: 2, goalsFor: 4, goalsAgainst: 13 },
];
